#!/usr/bin/env perl
use Mojolicious::Lite;

my @entries = (); # 空の配列を宣言

get '/' => sub {
  my $c = shift;
  $c->stash(entries => \@entries);
  $c->render('index');
};

post '/post' => sub {
  my $c = shift;
  my $entry = $c->param('body');
  push @entries , $entry;
  #$c->stash(entry => $entry);
  #$c->render('post');
  $c->redirect_to('/');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title '入力フォーム';
%= form_for '/post' => method => 'POST' => begin
  %= text_field 'body'
  %= submit_button '投稿する'
% end
% for my $entry (@{$entries}) {
    <p><%= $entry %></p>
% }

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

@@ post.html.ep
% # 新しいテンプレートを用意する
% layout 'default';
% # タイトルを変更
% title '出力';
% # 投稿先などを変更
%= form_for '/post' => method => 'POST' => begin
  %= text_field 'body'
  %= submit_button '投稿する'
% end
<p><%= $entry %></p>
